# Generated by Django 5.2.6 on 2025-10-01 15:25

import student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_course_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=32)),
                ('lname', models.CharField(max_length=32)),
                ('rank', models.CharField(choices=[('prof', 'Professor'), ('assc_prof', 'Assc Professor'), ('asst_prof', 'Asst Professor'), ('instructor', 'Instructor'), ('adjunct', 'Adjunct')], default='adjunct', max_length=12)),
            ],
            options={
                'ordering': ['lname', 'fname'],
            },
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['dept', 'course_num']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['lname', 'fname']},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_advisor',
            field=models.ForeignKey(default=student.models.get_default_advisor, on_delete=models.SET(student.models.get_default_advisor), related_name='advisees', to='student.advisor'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('dept', 'course_num'), name='unique_course'),
        ),
    ]
