# Generated by Django 5.2.6 on 2025-10-01 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_instructor_alter_course_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instructor',
        ),
    ]
